import { cardo, open_Sans } from "@/libs/fonts";
import { SkillCard } from "../ui";

export default function Skills() {
  const Data = [
    {
      id: 1,
      cardType: "water",
      title: "CSS",
      type: "water",
      imageLink: "/skillsIcons/CSS3_logo.svg",
      HP: "130",
      Attack: "65",
      Defense: "60",
      Speed: "65",
      Ability: "Charm",
      HiddenAbility: "Hydration",
    },
    {
      id: 2,
      cardType: "electric",
      title: "Javascript",
      type: "electric",
      imageLink: "/skillsIcons/Javascript-shield.webp",
      HP: "85",
      Attack: "95",
      Defense: "80",
      Speed: "130",
      Ability: "Control",
      HiddenAbility: "Quick Feet",
    },
    {
      id: 3,
      cardType: "psychic",
      title: "Bootstrap",
      type: "psychic",
      imageLink: "/skillsIcons/Bootstrap_logo.svg",
      HP: "65",
      Attack: "130",
      Defense: "60",
      Speed: "65",
      Ability: "Resize",
      HiddenAbility: "Guts",
    },
    {
      id: 4,
      cardType: "wind",
      title: "React.js",
      type: "atom",
      imageLink: "/skillsIcons/React-icon.svg",
      HP: "105",
      Attack: "90",
      Defense: "95",
      Speed: "130",
      Ability: "Smart",
      HiddenAbility: "Imperative",
    },
    {
      id: 13,
      cardType: "dark",
      title: "Next.js",
      type: "glass",
      imageLink: "/skillsIcons/nextjs-icon.webp",
      HP: "95",
      Attack: "65",
      Defense: "70",
      Speed: "55",
      Ability: "Time Freezing",
      HiddenAbility: "Camouflage",
    },
    {
      id: 9,
      cardType: "earth",
      title: "MERN",
      type: "earth",
      imageLink: "/skillsIcons/Mernstack.webp",
      HP: "125",
      Attack: "130",
      Defense: "105",
      Speed: "95",
      Ability: "Flow",
      HiddenAbility: "Hexagonical",
    },
    {
      id: 7,
      cardType: "fairy",
      title: "THREE.JS",
      type: "fairy",
      imageLink: "/skillsIcons/Three.js_Icon.svg",
      HP: "95",
      Attack: "105",
      Defense: "90",
      Speed: "80",
      Ability: "Reality",
      HiddenAbility: "Physical",
    },

    {
      id: 6,
      cardType: "water",
      title: "WORDPRESS",
      type: "ice",
      imageLink: "/skillsIcons/Wordpress_logo.webp",
      HP: "65",
      Attack: "60",
      Defense: "110",
      Speed: "65",
      Ability: "Immortality",
      HiddenAbility: "Ice Body",
    },
    {
      id: 5,
      cardType: "ice",
      title: "PHP",
      type: "snow",
      imageLink: "/skillsIcons/PHP-logo.svg",
      HP: "85",
      Attack: "105",
      Defense: "90",
      Speed: "110",
      Ability: "Synchronize",
      HiddenAbility: "Bouncy",
      imgStyle: { maxHeight: 105 + "px" },
    },
    {
      id: 11,
      cardType: "water",
      title: "React Native",
      type: "Atom",
      imageLink: "/skillsIcons/react-native_logo.png",
      HP: "105",
      Attack: "95",
      Defense: "110",
      Speed: "80",
      Ability: "One shot",
      HiddenAbility: "Inner Focus",
    },
    {
      id: 12,
      cardType: "ice",
      title: "UNITY",
      type: "shadow",
      imageLink: "/skillsIcons/Unity_Technologies_logo.svg",
      HP: "85",
      Attack: "125",
      Defense: "80",
      Speed: "70",
      Ability: "Enjoyment",
      HiddenAbility: "Storytelling",
    },
    {
      id: 8,
      cardType: "grass",
      title: "C#",
      type: "grass",
      imageLink: "/skillsIcons/C_Sharp_wordmark.svg",
      HP: "65",
      Attack: "110",
      Defense: "130",
      Speed: "95",
      Ability: "Elasticity",
      HiddenAbility: "Chlorophyll",
    },
    {
      id: 14,
      cardType: "wind",
      title: "Photoshop",
      type: "wind",
      imageLink: "/skillsIcons/Adobe_Photoshop_CC_icon.svg",
      HP: "85",
      Attack: "110",
      Defense: "130",
      Speed: "85",
      Ability: "Stretching",
      HiddenAbility: "Pixilate",
    },
    {
      id: 15,
      cardType: "normal",
      title: "Illustrator",
      type: "magic",
      imageLink: "/skillsIcons/Adobe_Illustrator_CC_icon.svg",
      HP: "65",
      Attack: "110",
      Defense: "130",
      Speed: "95",
      Ability: "Regen",
      HiddenAbility: "Shapelessness",
    },
    {
      id: 16,
      cardType: "water",
      title: "Premier pro",
      type: "storm",
      imageLink: "/skillsIcons/Adobe_Premiere_Pro_CC_icon.svg",
      HP: "75",
      Attack: "110",
      Defense: "120",
      Speed: "95",
      Ability: "Flying",
      HiddenAbility: "Manipulation",
    },
    {
      id: 17,
      cardType: "electric",
      title: "Blender",
      type: "electric",
      imageLink: "/skillsIcons/Blender_logo_no_text.svg",
      HP: "65",
      Attack: "110",
      Defense: "130",
      Speed: "95",
      Ability: "X-Ray",
      HiddenAbility: "Dimension",
    },
    {
      id: 18,
      cardType: "dark",
      title: "Framer",
      type: "dark",
      imageLink: "/skillsIcons/framer_logo.webp",
      HP: "65",
      Attack: "110",
      Defense: "95",
      Speed: "120",
      Ability: "Predicting",
      HiddenAbility: "Magic",
    },
  ];
  return (
    <section id="skills">
      <div className="timeline-header">
        <h2 className={cardo.className + " timeline-header__title"}>
          My skills
        </h2>
        <h3 className={" timeline-header__subtitle"}>
          DISCOVER MY SUPERPOWERS
        </h3>
      </div>
      <div id="cards" className={open_Sans.className}>
        {Data &&
          Data.map((skill) => {
            return <SkillCard {...skill} key={skill.id} />;
          })}
      </div>
    </section>
  );
}
